---
id: wellswood_cave
name: Cave
width: 42
height: 26
generate: false
layers:
  - base
  - base2
  - base3
  - prop
  - object
  - aerial
entity_layer: 3
actors: []
props: []
encounters: []
transitions: []
triggers: []
visibility_tile: gui/area_invis
explored_tile: gui/area_unexplored
max_vis_distance: 12
max_vis_up_one_distance: 6
terrain:
  tileset/cave_top_outer_edge_se:
    - - 26
      - 10
  tileset/cave_top_inner_edge_sw:
    - - 20
      - 0
    - - 22
      - 2
    - - 24
      - 4
    - - 32
      - 2
    - - 40
      - 12
    - - 40
      - 4
    - - 38
      - 2
    - - 36
      - 0
  tileset/cave_top_outer_edge_s:
    - - 2
      - 2
    - - 4
      - 2
    - - 6
      - 2
    - - 10
      - 0
    - - 12
      - 0
    - - 14
      - 0
    - - 16
      - 0
    - - 18
      - 0
    - - 28
      - 2
    - - 30
      - 2
  cave_top_tunnel_s:
    - - 36
      - 12
  tileset/cave_top_edge_overlap_w:
    - - 24
      - 6
    - - 32
      - 4
    - - 40
      - 14
    - - 40
      - 6
  tileset/rocks_dark_base_variant1:
    - - 20
      - 14
  tileset/cave_top_edge_overlap_e:
    - - 0
      - 4
    - - 26
      - 4
  tileset/cave_top_outer_edge_ne:
    - - 6
      - 22
    - - 28
      - 16
  tileset/cave_top_edge_overlap_se:
    - - 0
      - 6
    - - 26
      - 6
  cave_top_tunnel_n:
    - - 36
      - 11
  tileset/cave_wall_w:
    - - 24
      - 12
    - - 32
      - 14
    - - 36
      - 4
  cave_entrance_large_e:
    - - 38
      - 12
  tileset/cave_wall_se:
    - - 8
      - 6
    - - 26
      - 14
  tileset/rocks_dark_base_variant2:
    - - 28
      - 6
    - - 30
      - 6
    - - 32
      - 6
    - - 32
      - 8
    - - 30
      - 8
    - - 28
      - 10
    - - 30
      - 10
    - - 32
      - 10
    - - 32
      - 12
    - - 28
      - 12
    - - 28
      - 14
    - - 30
      - 14
    - - 32
      - 14
    - - 30
      - 16
    - - 32
      - 16
    - - 40
      - 16
    - - 40
      - 18
    - - 38
      - 18
    - - 36
      - 18
    - - 32
      - 18
    - - 30
      - 18
    - - 28
      - 18
    - - 28
      - 20
    - - 28
      - 22
    - - 30
      - 22
    - - 32
      - 20
    - - 32
      - 22
    - - 34
      - 22
    - - 36
      - 22
    - - 38
      - 22
    - - 38
      - 20
    - - 40
      - 20
    - - 40
      - 22
    - - 22
      - 14
    - - 14
      - 12
    - - 6
      - 12
  tileset/cave_top_inner_edge_ne:
    - - 0
      - 22
    - - 28
      - 22
    - - 34
      - 10
  cave_entrance_large_c:
    - - 36
      - 12
  tileset/cave_top_inner_edge_nw:
    - - 24
      - 18
    - - 22
      - 20
    - - 20
      - 22
    - - 40
      - 22
    - - 40
      - 10
  tileset/rocks_dark_base_variant3:
    - - 24
      - 14
    - - 14
      - 10
    - - 8
      - 8
    - - 12
      - 20
  tileset/cave_top_outer_edge_w:
    - - 10
      - 24
    - - 32
      - 8
    - - 32
      - 10
    - - 40
      - 20
    - - 40
      - 18
  tileset/cave_top_edge_overlap_sw:
    - - 24
      - 8
    - - 32
      - 6
    - - 40
      - 16
    - - 40
      - 8
  cave_top_tunnel_se:
    - - 38
      - 12
  tileset/cave_top_outer_edge_nw:
    - - 22
      - 18
    - - 20
      - 20
    - - 10
      - 22
    - - 24
      - 16
  tileset/cave_top_inner_edge_se:
    - - 0
      - 2
    - - 8
      - 0
    - - 26
      - 2
    - - 34
      - 0
  tileset/cave_top_edge_overlap_bot_w:
    - - 20
      - 2
    - - 22
      - 4
    - - 38
      - 4
  cave_top_tunnel_ne:
    - - 38
      - 11
  cave_top_tunnel_nw:
    - - 34
      - 10
    - - 35
      - 11
  tileset/cave_wall_nw:
    - - 8
      - 4
  tileset/rocks_dark_base:
    - - 10
      - 24
    - - 8
      - 24
    - - 6
      - 24
    - - 8
      - 22
    - - 6
      - 22
    - - 10
      - 22
    - - 12
      - 22
    - - 14
      - 22
    - - 16
      - 22
    - - 18
      - 22
    - - 20
      - 22
    - - 20
      - 20
    - - 22
      - 20
    - - 22
      - 18
    - - 24
      - 18
    - - 24
      - 16
    - - 24
      - 12
    - - 24
      - 10
    - - 24
      - 8
    - - 22
      - 8
    - - 20
      - 8
    - - 20
      - 6
    - - 18
      - 6
    - - 18
      - 4
    - - 16
      - 4
    - - 14
      - 4
    - - 12
      - 4
    - - 10
      - 4
    - - 8
      - 4
    - - 8
      - 6
    - - 6
      - 6
    - - 4
      - 6
    - - 2
      - 6
    - - 0
      - 6
    - - 0
      - 8
    - - 0
      - 10
    - - 0
      - 12
    - - 0
      - 14
    - - 0
      - 16
    - - 0
      - 18
    - - 0
      - 20
    - - 0
      - 22
    - - 2
      - 22
    - - 4
      - 22
    - - 2
      - 20
    - - 4
      - 20
    - - 6
      - 20
    - - 8
      - 20
    - - 10
      - 20
    - - 14
      - 20
    - - 16
      - 20
    - - 18
      - 20
    - - 20
      - 18
    - - 18
      - 18
    - - 16
      - 18
    - - 14
      - 18
    - - 12
      - 18
    - - 10
      - 18
    - - 8
      - 18
    - - 6
      - 18
    - - 4
      - 18
    - - 2
      - 18
    - - 2
      - 16
    - - 2
      - 14
    - - 2
      - 12
    - - 2
      - 10
    - - 2
      - 8
    - - 4
      - 8
    - - 4
      - 10
    - - 4
      - 12
    - - 4
      - 14
    - - 4
      - 16
    - - 6
      - 16
    - - 6
      - 14
    - - 6
      - 10
    - - 6
      - 8
    - - 8
      - 10
    - - 8
      - 12
    - - 8
      - 14
    - - 8
      - 16
    - - 10
      - 16
    - - 10
      - 14
    - - 10
      - 12
    - - 10
      - 10
    - - 10
      - 8
    - - 10
      - 6
    - - 12
      - 6
    - - 14
      - 6
    - - 16
      - 6
    - - 16
      - 8
    - - 18
      - 8
    - - 22
      - 10
    - - 22
      - 12
    - - 20
      - 10
    - - 18
      - 10
    - - 16
      - 10
    - - 14
      - 8
    - - 12
      - 8
    - - 12
      - 10
    - - 12
      - 12
    - - 16
      - 12
    - - 18
      - 12
    - - 20
      - 12
    - - 22
      - 16
    - - 20
      - 16
    - - 18
      - 14
    - - 18
      - 16
    - - 16
      - 16
    - - 16
      - 14
    - - 14
      - 14
    - - 12
      - 14
    - - 12
      - 16
    - - 14
      - 16
    - - 26
      - 16
    - - 26
      - 14
    - - 26
      - 12
    - - 26
      - 10
    - - 26
      - 8
    - - 26
      - 6
    - - 34
      - 20
    - - 36
      - 20
    - - 34
      - 18
    - - 28
      - 16
    - - 30
      - 12
    - - 28
      - 8
    - - 30
      - 20
    - - 34
      - 16
    - - 36
      - 16
    - - 38
      - 16
    - - 34
      - 10
    - - 34
      - 8
    - - 34
      - 6
    - - 34
      - 4
    - - 34
      - 2
    - - 36
      - 2
    - - 36
      - 4
    - - 36
      - 6
    - - 38
      - 6
    - - 38
      - 8
    - - 36
      - 8
    - - 40
      - 8
    - - 40
      - 10
    - - 38
      - 10
    - - 36
      - 10
  tileset/cave_wall_ne:
    - - 18
      - 4
    - - 20
      - 6
    - - 38
      - 6
  tileset/cave_wall_s:
    - - 2
      - 6
    - - 4
      - 6
    - - 6
      - 6
    - - 10
      - 4
    - - 12
      - 4
    - - 14
      - 4
    - - 16
      - 4
    - - 22
      - 8
    - - 28
      - 6
    - - 30
      - 6
  tileset/cave_top_edge_overlap_bot_e:
    - - 8
      - 2
  tileset/cave_wall_c:
    - - 22
      - 6
    - - 20
      - 4
    - - 6
      - 4
    - - 4
      - 4
    - - 2
      - 4
    - - 10
      - 2
    - - 12
      - 2
    - - 14
      - 2
    - - 16
      - 2
    - - 18
      - 2
    - - 30
      - 4
    - - 28
      - 4
  tileset/cave_top_outer_edge_sw:
    - - 24
      - 10
    - - 32
      - 12
    - - 36
      - 2
  cave_entrance_large_w:
    - - 34
      - 12
  tileset/cave_top_outer_edge_e:
    - - 0
      - 8
    - - 0
      - 10
    - - 0
      - 12
    - - 0
      - 14
    - - 0
      - 16
    - - 0
      - 18
    - - 0
      - 20
    - - 6
      - 24
    - - 26
      - 8
    - - 28
      - 18
    - - 28
      - 20
    - - 34
      - 8
    - - 34
      - 6
    - - 34
      - 4
    - - 34
      - 2
  tileset/cave_top_base:
    - - 14
      - 24
    - - 16
      - 24
    - - 18
      - 24
    - - 20
      - 24
    - - 22
      - 24
    - - 22
      - 22
    - - 24
      - 20
    - - 24
      - 22
    - - 24
      - 24
    - - 4
      - 24
    - - 2
      - 24
    - - 0
      - 24
    - - 24
      - 2
    - - 24
      - 0
    - - 22
      - 0
    - - 6
      - 0
    - - 4
      - 0
    - - 2
      - 0
    - - 0
      - 0
    - - 12
      - 24
    - - 40
      - 2
    - - 38
      - 0
    - - 40
      - 0
    - - 26
      - 0
    - - 28
      - 0
    - - 30
      - 0
    - - 32
      - 0
    - - 26
      - 18
    - - 26
      - 20
    - - 26
      - 22
    - - 26
      - 24
    - - 28
      - 24
    - - 30
      - 24
    - - 32
      - 24
    - - 34
      - 24
    - - 36
      - 24
    - - 38
      - 24
    - - 40
      - 24
  tileset/cave_top_outer_edge_n:
    - - 18
      - 22
    - - 16
      - 22
    - - 2
      - 22
    - - 4
      - 22
    - - 14
      - 22
    - - 12
      - 22
    - - 26
      - 16
    - - 30
      - 22
    - - 32
      - 22
    - - 34
      - 22
    - - 36
      - 22
    - - 38
      - 22
    - - 36
      - 10
    - - 38
      - 10
  tileset/cave_wall_e:
    - - 26
      - 12
  tileset/cave_wall_sw:
    - - 18
      - 6
    - - 20
      - 8
    - - 24
      - 14
    - - 32
      - 16
    - - 36
      - 6
    - - 38
      - 8
  cave_top_tunnel_sw:
    - - 35
      - 12
elevation:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 0
  - 0
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 0
  - 0
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1