---
id: dungeon_level03
name: Dungeon Level 3
generator:
  id: dungeon
  transitions:
    - to: dungeon_level02
      kind: level_up
      hover_text: "Up"
    - to: dwarven_enclave
      kind: level_down
      hover_text: "Down"
  props:
    passes:
      - kinds:
          chest_medium_level1_misc:
            weight: 1
          chest_small_level1_misc:
            weight: 1
          chest_xl_level5_armor:
            weight: 1
          chest_xl_level5_weapons:
            weight: 1
        spacing: 8
        placement_attempts: 100
        allowable_regions: [ Room ]
        require_passable: true
  encounters:
    passes:
      - kinds:
          goblins_level2:
            weight: 1
          goblins_level3:
            weight: 2
        spacing: 20
        chance_per_room: 75 
        allowable_regions: [ Room ]
        size: [10, 10]
width: 128
height: 128
visibility_tile: gui/area_invis
explored_tile: gui/area_unexplored
max_vis_distance: 16
max_vis_up_one_distance: 6
world_map_location: moonmouth
on_rest:
  Disabled:
    message: "You may not rest here."
location_kind: Indoors
layers:
  - terrain_base
  - terrain_border
  - walls
  - walls_top
  - prop
  - object
  - object_interior
  - decoration
  - walls_aerial
  - aerial
  - aerial_prop
entity_layer: 7
actors: []
props: []
encounters: []
transitions: []
triggers: []
terrain:
  kinds: []
  entries: ""
walls:
  kinds: []
  entries: ""
layer_set: {}
elevation: ""
