---
id: dungeon_entrance
name: Dungeon Entrance
generator:
  id: cave
  transitions:
    - to: dungeon_level01
      kind: level_down
      hover_text: "Down"
width: 128
height: 128
visibility_tile: gui/area_invis
explored_tile: gui/area_unexplored
max_vis_distance: 16
max_vis_up_one_distance: 6
world_map_location: moonmouth
on_rest:
  Disabled:
    message: "You may not rest here."
location_kind: Indoors
layers:
  - terrain_base
  - terrain_border
  - walls
  - walls_top
  - prop
  - object
  - object_interior
  - decoration
  - walls_aerial
  - aerial
  - aerial_prop
entity_layer: 7
actors: []
props: []
encounters: []
transitions:
  - from:
      x: 64
      y: 64
    size: 4by4
    to:
      Area:
        id: moonmouth
        x: 67
        y: 57
    hover_text: To Outside
    image_display: empty
triggers: []
terrain:
  kinds: []
  entries: ""
walls:
  kinds: []
  entries: ""
layer_set: {}
elevation: ""
