if: tag IS present
sudo: required
services:
  - docker
language: rust
rust:
- stable
matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-musl TARGET_NAME=linux64
    - env: TARGET=x86_64-pc-windows-gnu TARGET_NAME=win64 TARGET_EXTENSION=.exe
    - env: TARGET=x86_64-apple-darwin TARGET_NAME=osx64 TARGET_EXTENSION=.app
cache: cargo
script:
  - cargo install cross
  - cross build --release --target $TARGET
before_cache:
  # Travis can't cache files that are not readable by "others"
- chmod -R a+r $HOME/.cargo
before_deploy:
- cp target/$TARGET/release/main$TARGET_EXTENSION ./sulis$TARGET_EXTENSION
- git archive HEAD --prefix=sulis/ --format=zip -o sulis-$TRAVIS_TAG-$TARGET_NAME.zip
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: fO8irum986Dq51CGKMHRVpny81BaKv4BLYw5/KffzHEAerBoiTe/6F8t8nlyziDqTDI75qHM8eSRsjnvbD+sL6fXc/PSdwN/T1zZ6+x9nozcBrRWASOTLwQ2NXi3jS43EfcrwJAzF887yJBUdMshD7NreWianVYa8aR834/fvlpYLvTA/STJErOZEQ5LLimOuGCT4TI/l6l3sZmJlG8LGhrD2aSHMVHapwCoGXzW3GJYXoatAa+JUsBOokb2GVFy8bPqdIzSpqNTbZaA9rUMJEjjOy+34q+YWFsoaA5s/lOGJKyqFZ56GYqm/ROFpyLgyyUPOcB9GEscTeGCTPVSVyH70rlrSl4erHpu+A+1tHsN5roGLHysaEdzB5797je5fLdFuW3XVWxOr1HCNIK840PBNFkSeFrc+Gsst9f+5mSVWg2bmcubrWdAyyuzzQhRQO7XARq94g/yCWrEnzBo++WRPTrPknyJkaVz19E1YMzroipSyXq7NsC0izTBm952NsdHlWm4OVtbPtQ/YK3TWKXSCGOXTxdwFERtN7HUyjL3htq4LWshn8PUCs22qVX7wWtKBKZAloA624Ei0q65ofTysf+cip+MaAOedKTCNZIDkrPGuobaThoQ8U3aJdAWR6b3WnfaC+Ui3q+w3LI9HB+CM4KmmPIpK+UiSjpCePY=
  file: sulis-$TRAVIS_TAG-$TARGET_NAME.tar.gz
  on:
    repo: Grokmoo/sulis
    all_branches: true
    tags: true
