[package]
name = "game"
version = "0.1.0"
authors = ["Jared Stephen <grok_moo@yahoo.com>"]

[workspace]
members = [
    "grt",
]

[dependencies]
grt = { path = "grt" }

backtrace = "0.3"
flexi_logger = "0.6"
image = "0.18"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
