[package]
name = "game"
version = "0.1.0"
authors = ["Jared Stephen <grok_moo@yahoo.com>"]

[workspace]
members = [
    "grt",
]

[dependencies]
grt = { path = "grt" }
backtrace = "0.3.4"
flexi_logger = "0.6"
log = "0.3"
