[package]
name = "game"
version = "0.1.0"
authors = ["Jared Stephen <grok_moo@yahoo.com>"]

[dependencies]
termion = { git = "https://github.com/mcgoo/termion", branch = "windows" }
pancurses = "0.13.0"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

toml = "0.4.5"
