[package]
name = "sulis"
version = "0.1.0"
authors = ["Jared Stephen <grok_moo@yahoo.com>"]

[workspace]
members = [
    "sulis_engine",
	"sulis_rules",
	"sulis_module",
	"sulis_state",
	"sulis_view",
]

[dependencies]
sulis_engine = { path = "sulis_engine" }
sulis_rules = { path = "sulis_rules" }
sulis_module = { path = "sulis_module" }
sulis_state = { path = "sulis_state" }
sulis_view = { path = "sulis_view" }

backtrace = "0.3"
flexi_logger = "0.6"
log = "0.4"
