---
# The main game configuration file.  User preferences are set here.

display:
    # Display Adapter - Glium is the only choice for now
    adapter: Auto

    # Display Mode - Fullscreen, BorderlessWindow, Window
    mode: Window

    # Which monitor to display on, starting from 0
    monitor: 0

    # size of the graphical display in pixels
    width_pixels: 1600
    height_pixels: 900

    # UI scaling - Standard
    width: 320
    height: 180

    # UI scaling - Small
    # width: 368
    # height: 207

    # in frames per second
    frame_rate: 60

    # This scales the overall speed of all game animations, in milliseconds
    # Larger values make animations take longer
    animation_base_time_millis: 50

    # The name of the default font used to render text when no font is specified
    default_font: normal

    # The default mouse pointer
    default_cursor: mouse

resources:
    # all resources are subdirectories under this
    directory: data

input:
    # whether moving the mouse to the screen edge will scroll the view
    edge_scrolling: false
    
    # scrolling rate for all scrolling methods
    scroll_speed: 1.5

    # a mapping of keyboard characters to game actions
    keybindings:
        KeyEscape: ShowMenu
        KeyI: ToggleInventory
        KeyC: ToggleCharacter
        KeyF: ToggleFormation
        KeySpace: EndTurn
        KeyDown: ScrollDown
        KeyUp: ScrollUp
        KeyLeft: ScrollLeft
        KeyRight: ScrollRight
        KeyPageUp: ZoomIn
        KeyPageDown: ZoomOut
        KeyF5: QuickSave
        KeyGrave: ToggleConsole
        KeyP: SelectAll

logging:
    # Log level may be error, warn, info, debug, or trace
    # Each level logs progressively more to log/main*.log with
    # trace logging the most and error logging the least.
    log_level: info

    # If set to true, log files are generated with a timestamp,
    # Meaning each run of the game will generate a unique log filename.
    # If false, each run will simply use the same main.log file.
    use_timestamps: false

    # If set to false, the log file is truncated at application startup;
    # all previous entries are removed.  If set to true, the previous log
    # entries are kept.  This option will have no effect if use_timestamps
    # is true, as this causes a new file to be used each time.
    append: true

# Defaults used by the editor when creating areas
editor:
  # The ID of the module that the editor will load
  module: twin_expanse

  transition_image: transition
  transition_size: 4by3
  cursor: "gui/white"
  area:
    filename: "editor_test"
    id: "editor_test"
    name: "Editor Test"
    encounter_tile: "gui/editor_encounter"
    visibility_tile: "gui/area_invis"
    explored_tile: "gui/area_unexplored"
    entity_layer: 5
    layers:
      - terrain_base
      - terrain_border
      - walls
      - walls_top
      - prop
      - object
      - walls_aerial
      - aerial
    elev_tiles:
      - gui/elev_lowest
      - gui/elev_lower
      - gui/elev_low
      - gui/elev_mid
      - gui/elev_high
      - gui/elev_higher
      - gui/elev_highest
...
