---
# The main game configuration file.  User preferences are set here.

display:
    # Uncomment Pancurses line for Windows, Termion for Unix
    # Note that the indentation must be consistent for all values!
    #adapter: Pancurses
    adapter: Termion

    # display character for the mouse cursor
    cursor_char: "█"

    # screen dimensions in characters
    width: 80
    height: 24

    # in frames per second
    frame_rate: 30

    # This scales the overall speed of all game animations, in milliseconds
    animation_base_time_millis: 50

resources:
    # all resources are subdirectories under this
    directory: data

input:
    # a mapping of keyboard characters to game actions
    keybindings:
        KeyUp: ScrollUp
        KeyLeft: ScrollLeft
        KeyDown: ScrollDown
        KeyRight: ScrollRight
        KeyW: MoveCursorUp
        KeyS: MoveCursorDown
        KeyA: MoveCursorLeft
        KeyD: MoveCursorRight
        KeySpace: ClickCursor
        KeyQ: Exit
        KeyI: ToggleInventory

logging:
    # Log level may be error, warn, info, debug, or trace
    # Each level logs progressively more to log/main*.log with
    # trace logging the most and error logging the least.
    log_level: trace

    # If set to true, log files are generated with a timestamp,
    # Meaning each run of the game will generate a unique log filename.
    # If false, each run will simply overwrite the previous log file.
    use_timestamps: false
...
