---
id: farmhouse01
name: Farmhouse
width: 36
height: 38
visibility_tile: gui/area_invis
explored_tile: gui/area_unexplored
max_vis_distance: 12
max_vis_up_one_distance: 6
world_map_location: wellswood
on_rest:
  Disabled:
    message: You cannot rest here.  Find an inn or temple.
location_kind: Indoors
layers:
  - terrain_base
  - terrain_border
  - walls
  - walls_top
  - prop
  - object
  - object_interior
  - decoration
  - walls_aerial
  - aerial
  - aerial_prop
entity_layer: 7
actors: []
props:
  - id: boiling_pot
    location:
      x: 31
      y: 25
    enabled: true
  - id: lantern
    location:
      x: 31
      y: 13
    enabled: true
  - id: door_single_02
    location:
      x: 26
      y: 19
    enabled: true
  - id: chest_small_level1_misc
    location:
      x: 12
      y: 7
    enabled: true
  - id: cabinet_med_01
    location:
      x: 32
      y: 5
    items:
      - quantity: 1
        item:
          id: longsword
          adjectives: []
      - quantity: 1
        item:
          id: shortbow
          adjectives: []
    enabled: true
  - id: cabinet_med_04
    location:
      x: 30
      y: 5
    enabled: true
  - id: cabinet_small_01
    location:
      x: 8
      y: 7
    enabled: true
encounters: []
transitions:
  - from:
      x: 25
      y: 33
    size: 4by3
    to:
      Area:
        id: wellswood_farms
        x: 7
        y: 11
    hover_text: To Farms
    image_display: empty
triggers:
  - kind: OnAreaLoad
    on_activate:
      - fire_script:
          id: farmhouse01
          func: on_area_load
    initially_enabled: true
terrain:
  kinds:
    - interior_wood02
    - interior_tile
  entries: ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD///////////////////////////////////////////////////////////////////////////8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD///////////////////////////////////////////////////8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD///////////////////////////////////////////////////8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD///////////////////////////////////////////////////8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD///////////////////////////////////////////////////8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD///////////////////////////////////////////////////8A/wD/AP8A/wD/AP//////AP8A/wD/AP8A/wD/AP8A/wD///////////////////////////////////////////////////////////////////////////////////8A////////////////////////////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/////////////////////////////////////////////////////////////////////////////////AP8A/wD/AP8B/wH/AP8A/wD/////////////////////////////////////////////////////////////////////////AP8B/wH/Af8B/wH/Af8B/wD/////////////////////////////////////////////////////////////////////////AP8B/wH/Af8B/wH/Af8B/wD/////////////////////////////////////////////////////////////////////////AP8B/wH/Af8B/wH/Af8B/wD/////////////////////////////////////////////////////////////////////////AP8B/wH/Af8B/wH/Af8B/wD/////////////////////////////////////////////////////////////////////////AP8B/wH/Af8B/wH/Af8B/wD/////////////////////////////////////////////////////////////////////////AP8B/wH/Af8B/wH/Af8B/wD/////////////////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/////////////////////////////////////////////////
walls:
  kinds:
    - interior_wood
  entries: AAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wAAAf8AAAH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wAAAf8AAAH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wAAAf8AAAH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AP8B/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AP8B/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A
layer_set:
  tileset/plate03: ACAAHA==
  tileset/bar_horiz_e: ABQAFg==
  tileset/bar_vert_east_c: ACAAHgAgACAAIAAi
  tileset/plate05: ABYAHg==
  tileset/interior_wood_outer_edge_sw: ABAACAAcABI=
  tileset/bar_vert_east_n: ACAAHA==
  tileset/interior_wood_inner_edge_se: AAIAAgASABIAEgAC
  tileset/cabinet_bot_02: AAoABw==
  tileset/cabinet02: ABwABA==
  tileset/building_wood_outer_edge_s: AAIABAAeAAQAIAAEACIABAAiABQAEgAUABIABAAUAAQAFgAEABgABAAaAAQAHAAEAAQABAAGAAQACAAEAAoABAAMAAQADgAEABAABAAUABQAFgAUAB4AFAAgABQ=
  tileset/cabinet_bot_01: ABQABw==
  tileset/cabinet_top_03: ABQABQ==
  tileset/interior_wood_base: AAAAFgACABYABAAWAAYAFgAIABYACgAWAAwAFgAAABgAAgAYAAQAGAAGABgACAAYAAoAGAAMABgAAAAaAAIAGgAEABoABgAaAAgAGgAKABoADAAaAAAAHAACABwABAAcAAYAHAAIABwACgAcAAwAHAAAAB4AAgAeAAQAHgAGAB4ACAAeAAoAHgAMAB4AAAAgAAIAIAAEACAABgAgAAgAIAAKACAADAAgAAAAIgACACIABAAiAAYAIgAIACIACgAiAAwAIgAAACQAAgAkAAQAJAAGACQACAAkAAoAJAAMACQAAAAAAAIAAAAAAAIAAAAEAAAABgAAAAgAAAAKAAAADAAAAA4AAAAQAAAAEgAAABQAAgASAAQAEgAGABIACAASAAIAFAAEABQABgAUAAgAFAAeAAAAIAAAACIAAAAOABYAEAAWAA4AGAAQABgADgAaABAAGgAOABwAEAAcAA4AHgAQAB4ADgAgABAAIAAOACIAEAAiAA4AJAAQACQACgASAAwAEgAOABIAEAASAAoAFAAMABQADgAUABAAFAASAAAAFAAAABYAAAAYAAAAGgAAABwAAAAEAAAABgAAAAgAAAAKAAAADAAAAA4AAAAQAAA=
  tileset/interior_wood_inner_edge_nw: ACIAJAAiABA=
  tileset/wine_bottle02: ABcAFg==
  tileset/table03: AB8ADQ==
  tileset/bar_horiz_w: ABgAFg==
  tileset/interior_wood_outer_edge_e: AAIABAACAAYAAgAIAAIACgACAAwAAgAOABIAGAASABoAEgAcABIAHgASACAAEgAiABIAFgASABQAEgAEABIABg==
  tileset/interior_wood_inner_edge_sw: ACIAAgAiABIAEAAC
  tileset/interior_wood_outer_edge_ne: ABgAEA==
  tileset/cabinet04: ABoABA==
  tileset/interior_wood_outer_edge_se: ABIACAAYABI=
  tileset/interior_wood02_base: ABIAIAASACIAEgAkABQAJAAWACQAIgAiABgAJAAaACQAHAAkAB4AJAAgACQAIgAkAB4AFgAgABYAIgAWACIAGAAiABwAIgAeABIAFAAUABQAFgAUABoAFAAcABQAEgAWABQAFgAYABYAEgAYABIAGgASABwAEgAeABIABgAUAAYAFgAGABgABgASAAgAFAAIABYACAAYAAgAEgAKABQACgAWAAoAGAAKABIADAAUAAwAGAAMABIADgAUAA4AFgAOABgADgASABAAFAAQABYAEAAYABAAGgAGAB4ABgAiAAYAGgAIABwACAAeAAgAIAAIACIACAAcAAoAHgAKACAACgAiAAoAGgAMABwADAAeAAwAIAAMACIADAAaAA4AHAAOAB4ADgAgAA4AIgAOABoAEAAcABAAHgAQACAAEAAGAAQACAAEAAoABAAMAAQADgAEABAABAAOAAYAEAAGAA4ACAAQAAgADgAKABAACgAOAAwAEAAMAA4ADgAQAA4AAgAGAAQABgAGAAYACAAGAAoABgAMAAYAAgAIAAQACAAIAAgACgAIAAwACAACAAoABAAKAAYACgAIAAoACgAKAAwACgACAAwACAAMAAoADAAMAAwAAgAOAAQADgAGAA4ACAAOAAoADgAMAA4AAgAQAAQAEAAGABAACAAQAAoAEAAMABAABgAIAAYADAAEAAwAFgAMABoACgAiACAAGgAS
  tileset/cabinet03: ABgABA==
  tileset/interior_wood_outer_edge_nw: ABwAEA==
  tileset/table04: AA4ACg==
  tileset/building_wood_outer_edge_se: ABIACgAYABQ=
  tileset/interior_tile_base: ABoAGgAcABoAGAAYABgAGgAUABgAFgAYABQAGgAWABoAFAAcABoAHAAaAB4AHAAcABwAHgAeABwAIAAcAB4AHgAgAB4AGgAgABwAIAAaACIAHAAiABgAIAAYACIAFAAiABYAIgAUAB4AFAAgABYAIAAWABwAGAAcABYAHgAYAB4AHgAgACAAIAAeACIAIAAiAB4AGAAgABgAHgAaACAAGgAaABYAHAAWABoAGAAcABg=
  tileset/interior_wood_inner_edge_ne: AAIAEAASACQ=
  tileset/bucket_full: AA4ACA==
  tileset/interior_wood_outer_edge_s: AB4AAgAgAAIAFAACABYAAgAYAAIAGgACABwAAgAEAAIABgACAAgAAgAKAAIADAACAA4AAgAUABIAFgASAB4AEgAgABI=
  bed_small02: AAQADA==
  01entry_light: ABgAIA==
  tileset/interior_wood02_base_variant1: ACIAGgAYABQAFgAWABwABgAgAAYAIgAQ
  tileset/cabinet_top_04: AAgABQ==
  table_large01: ABQAHA==
  bed_small01: AAQACA==
  tileset/building_wood_outer_edge_sw: ABAACgAcABQ=
  tileset/plate08: ABQAFg==
  tileset/chair06: AB0ADQ==
  tileset/bar_horiz_c: ABYAFg==
  tileset/interior_wood_outer_edge_n: AAQAEAAGABAACAAQABQAJAAWACQAGAAkABoAJAAcACQAHgAkACAAJAAKABAADAAQAA4AEAAQABAAEgAQABQAEAAWABAAHgAQACAAEA==
  tileset/cabinet_top_01: AAoABQ==
  tileset/chair07: AA4ADA==
  tileset/rug_small01: ABoAIg==
  tileset/interior_wood_outer_edge_w: ACIABAAiAAYAIgAIACIAGAAiABoAIgAcACIAHgAiACAAIgAiACIACgAiAAwAIgAOACIAFAAiABYAEAAEABAABg==
  tileset/cabinet_bot_04: ABYABg==
  tileset/chair05: AB8ACw==
  tileset/bottles02: ABUAGw==
elevation: AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAAAAAICAgICAgAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAAAAAICAgICAgAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAAAAAICAgICAgAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAAAAAICAgICAgAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAAAAAICAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgICAgICAgICAgICAgIAAAICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAAAICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAAAICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAAAICAgICAgICAgICAgICAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC