---
id: farmhouse02
name: Farmhouse
width: 34
height: 34
visibility_tile: gui/area_invis
explored_tile: gui/area_unexplored
max_vis_distance: 12
max_vis_up_one_distance: 6
world_map_location: wellswood
on_rest:
  Disabled:
    message: You cannot rest here.  Find an inn or temple.
location_kind: Indoors
generate: false
layers:
  - terrain_base
  - terrain_border
  - walls
  - walls_top
  - prop
  - object
  - object_interior
  - decoration
  - walls_aerial
  - aerial
  - aerial_prop
entity_layer: 7
actors: []
props:
  - id: chest_small_level1_misc
    location:
      x: 8
      y: 5
    items: []
    enabled: true
    hover_text: ~
  - id: door_single_02
    location:
      x: 24
      y: 15
    items: []
    enabled: true
    hover_text: ~
  - id: door_single_02
    location:
      x: 8
      y: 15
    items: []
    enabled: true
    hover_text: ~
  - id: cabinet_small_01
    location:
      x: 4
      y: 6
    items: []
    enabled: true
    hover_text: ~
  - id: chest_small_level1_misc
    location:
      x: 12
      y: 28
    items: []
    enabled: true
    hover_text: ~
encounters: []
transitions:
  - from:
      x: 23
      y: 29
    size: 4by3
    to:
      Area:
        id: wellswood_farms
        x: 13
        y: 71
    hover_text: To Farms
    image_display: empty
triggers: []
terrain:
  kinds:
    - interior_wood02
    - interior_wood01
  entries: //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP///////////////////////////////////////////////////wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD///////////////////////////////////////////////////////////8A////////////////////AP///////////////////////////////////////////////////////////////////wD///////////////////8A////////////////////////////////////////////////////////////////////AP///////////////////wD///////////////////////////////////////////////////////////////////8A////////////////////AP///////////////////////////////////////////////////////////wD/AP8A/wD/AP8A//////8B/wH/Af8B/wH/Af8B////////////////////////////////////////////////////AP8A/wD/AP8A/wD//////wH/Af8B/wH/Af8B/wH///////////////////////////////////////////////////8A/wD/AP8A/wD/AP//////Af8B/wH/Af8B/wH/Af///////////////////////////////////////////////////wD/AP8A/wD/AP8A//////8B/wH/Af8B/wH/Af8B////////////////////////////////////////////////////AP8A/wD/AP8A/wD//////wH/Af8B/wH/Af8B/wH/////////////////////////////////////////////////////////////////////////Af8B/wH/Af8B/wH/Af///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////w==
walls:
  kinds:
    - interior_wood
  entries: AAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wD/Af8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wD/Af8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AP8B/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8A/wH/AAAB/wAAAf8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8AAAH/AAAB/wD/Af8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AP8B/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wH/AP8B/wD/Af8A/wH/AP8B/wD/Af8AAAH/AAAB/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wD/Af8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AAAB/wAAAf8A/wH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wAAAf8AAAH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wH/AP8B/wD/Af8A/wH/AP8B/wD/Af8AAAH/AAAB/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wD/Af8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AAAB/wAAAf8A/wH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wAAAf8AAAH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wH/AP8B/wD/Af8A/wH/AP8B/wD/Af8AAAH/AAAB/wD/Af8A/wH/AP8B/wD/Af8A/wH/AP8B/wD/Af8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8A/wH/AP8B/wD/Af8A/wH/AP8B/wD/Af8A/wH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wA=
layer_set:
  tileset/ropes01: ABYABA==
  tileset/interior_wood_outer_edge_n: AAIAHgAEAB4ABgAeAAgAHgAKAB4ADAAeABIAIAAUACAAFgAgABgAIAAaACAAHAAgAB4AIAAQAAwAEgAMABQADAAcAAwAHgAMAAIADAAEAAwADAAMAA4ADA==
  01entry_light: ABYAHA==
  tileset/interior_wood_outer_edge_ne: ABYADAAGAAw=
  tileset/cabinet_top_02: ABQAEQ==
  table_large01: ABoABg==
  tileset/book01: AAIAHA==
  tileset/building_wood_variant2: AAgAAg==
  tileset/cabinet_top_03: AAQABA==
  tileset/plate08: AB4AEg==
  tileset/interior_wood02_base: AAIAFAAEABQABgAUAAIAFgAEABYABgAWAAgAFAAMABQACAAWAAoAFgAMABYACAAYAAoAGAAMABgACAAaAAwAGgAIABwACgAcAAwAHAACABgABAAYAAYAGAACABoABAAaAAYAGgACABwABAAcAAYAHAAKABoACgAUAAIABgAEAAYABgAGAAIACAAEAAgABgAIAAIACgAEAAoABgAKAAgABgAIAAgACgAIAAgACgAKAAoADAAGAA4ABgAMAAgADgAIAAwACgAWAAYAFgAIABYACgAYAAYAGAAIABgACgAaAAYAHAAGAB4ABgAaAAgAHAAIAB4ACAAcAAoAHgAKABAABgASAAYAEAAIABIACAAUAAgAEAAKABIACgAUAAoACgAGAA4ACgAUAAYAGgAKABgADAAIAAwACAAOAAgAEAAIABIAGAAOABgAEAAYABI=
  tileset/building_wood_variant3: ABwAAg==
  tileset/bed_vert_01: AAIAEw==
  tileset/interior_wood_inner_edge_nw: AA4AHgAgACAAIAAM
  tileset/interior_wood_inner_edge_ne: AAAAHgAAAAwAEAAg
  tileset/cabinet_small_01: AAYAFA==
  tileset/interior_wood_outer_edge_se: ABYADgAGAA4=
  tileset/interior_wood_outer_edge_sw: ABoADgAKAA4=
  tileset/cabinet04: ABIAEA==
  tileset/plate05: ABwAEg==
  tileset/bar_vert_east_s: AB4AGg==
  tileset/interior_wood_outer_edge_nw: ABoADAAKAAw=
  tileset/bar_vert_east_c: AB4AFgAeABg=
  tileset/chair04: AB4ABgAeAAg=
  tileset/bar_horiz_w: AAYAHAAeABI=
  tileset/plate03: ABsACA==
  tileset/building_wood_outer_edge_s: AAAAAgACAAIABAACAAYAAgAKAAIADgACABAAAgASAAIAFAACABYAAgAYAAIAGgACAB4AAgAgAAIAAAAQACAAEAAQABAAEgAQABQAEAAcABAAHgAQAAIAEAAEABAADAAQAA4AEA==
  tileset/plate04: ABsABg==
  tileset/cabinet_bot_03: ABQAEw==
  tileset/building_wood_outer_edge_sw: ABoAEAAKABA=
  tileset/flour_sack_2by2: AAIACA==
  tileset/chair03: ABgABg==
  tileset/bucket_full: ABMAHg==
  tileset/interior_wood_outer_edge_e: AAAAAgAAAAQAAAAGAAAACAAAABoAAAAcAAAACgAAABAAAAASAAAAFAAAABYAAAAYABAAHgAQABYAEAAYABAAGgAQABwAEAAQABAAEgAQABQ=
  tileset/cabinet03: ABIAAg==
  tileset/building_wood_variant1: AAwAAg==
  tileset/cabinet_bot_04: AAYABA==
  tileset/lantern_off: AB4AGg==
  tileset/bottles01: ABoAEg==
  tileset/rug_small01: ABgAHgAGABY=
  tileset/sack_stack: AAIABA==
  tileset/cabinet_wide01: AAoAEQ==
  tileset/building_wood_outer_edge_se: ABYAEAAGABA=
  tileset/cabinet02: ABQAAg==
  tileset/interior_wood_base: AAAAIAACACAABAAgAAYAIAAIACAACgAgAAwAIAAOACA=
  tileset/interior_wood01_base: ABIAHAAUABwAFgAcABIAHgAUAB4AFgAeABgAHgAaAB4AHAAeAB4AHgAaABQAHAAUAB4AFAASABQAFAAUABYAFAAYABQAEgAWABQAFgAWABYAEgAYABQAGAAWABgAEgAaABQAGgAWABoAGAAWABoAFgAcABYAHgAWABgAGAAaABgAHgAYABgAGgAaABoAHAAaAB4AGgAYABwAGgAcABwAHAAeABwAHAAY
  tileset/interior_wood_inner_edge_se: AAAAAAAAAA4AEAAO
  tileset/bar_horiz_e: AAIAHAAaABI=
  tileset/bar_vert_east_n: AB4AFA==
  tileset/interior_wood_outer_edge_s: AAIAAAAEAAAABgAAAAgAAAAKAAAADAAAAA4AAAAQAAAAEgAAABQAAAAWAAAAGAAAABoAAAAcAAAAHgAAABIADgAUAA4AHAAOAB4ADgACAA4ABAAOAAwADg==
  tileset/bar_horiz_c: AAQAHAAcABI=
  tileset/wine_bottle02: AAYAEw==
  tileset/interior_wood_outer_edge_w: ACAAAgAgAAQAIAAGACAACAAgAAoADgAWAA4AGAAOABoADgAcACAAHgAgABAAIAASACAAFAAgABYAIAAYACAAGgAgABwADgAUAA4AEAAOABI=
  tileset/interior_wood_inner_edge_sw: ACAAAAAgAA4ADgAO
elevation: AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgICAgIAAAICAgICAgICAgICAgICAAACAgICAgICAgICAgICAgICAAACAgICAgICAgICAgICAgAAAgICAgICAgICAgICAgICAgAAAgICAgICAgICAgICAgIAAAICAgICAgICAgICAgICAgIAAAICAgICAgICAgICAgICAAACAgICAgICAgICAgICAgICAAACAgICAgICAgICAgICAgAAAgICAgICAgICAgAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAACAgICAAAAAAAAAAAAAAAAAAACAgICAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAACAgICAAAAAAAAAAAAAAAAAAACAgICAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAACAgICAAAAAAAAAAAAAAAAAAACAgICAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAACAgICAAAAAAAAAAAAAAAAAAACAgICAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAACAgICAgICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg==