---
id: rose_lake_guardhouse
name: Rose Lake Guardhouse
width: 42
height: 42
visibility_tile: gui/area_invis
explored_tile: gui/area_unexplored
max_vis_distance: 12
max_vis_up_one_distance: 6
world_map_location: rose_lake
on_rest:
  Disabled:
    message: You cannot rest here.  Find an inn or temple.
location_kind: Indoors
generate: false
layers:
  - terrain_base
  - terrain_border
  - walls
  - walls_top
  - prop
  - object
  - object_interior
  - decoration
  - walls_aerial
  - aerial
  - aerial_prop
entity_layer: 7
actors:
  - id: rose_guard01
    location:
      x: 31
      y: 29
    unique_id: rlg_guard01
  - id: rose_guard02
    location:
      x: 4
      y: 25
    unique_id: rlg_guard02
  - id: rose_guard03
    location:
      x: 6
      y: 35
    unique_id: rlg_guard03
  - id: rose_guard04
    location:
      x: 28
      y: 11
    unique_id: rlg_guard04
  - id: rose_guard05
    location:
      x: 18
      y: 6
    unique_id: rlg_guard05
props:
  - id: lantern
    location:
      x: 2
      y: 28
    items: []
    enabled: true
    hover_text: ~
  - id: lantern
    location:
      x: 11
      y: 10
    items: []
    enabled: true
    hover_text: ~
encounters: []
transitions:
  - from:
      x: 18
      y: 39
    size: 4by3
    to:
      Area:
        id: rose_lake
        x: 53
        y: 89
    hover_text: To Rose Lake
    image_display: empty
triggers: []
terrain:
  kinds:
    - interior_stone
    - interior_wood01
  entries: /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////wD/AP8A/wD///////////////////////////////////////////////////////////////////////////////////////////8A/wD/AP8A/wD/AP8A/wD/AP////////////////8A/wD/AP////////////////////////////////////////////////////////////////8A/wD/AP8A/wD/AP8A/wD/AP////////8A/wD/AP8A/wD/AP////////////////////////////////////////////////////////////////8A/wD/AP8A/wD/AP8A/wD/AP////////8A/wD/AP8A/wD/AP////////////////////////////////////////////////////////////////8A/wD/AP8A/wD/AP8A/wD/AP////////8A/wD/AP8A/wD/AP////////////////////////////////////////////////////////////////8A/wD/AP8A/wD/AP8A/wD/AP///wD/AP8A/wD/AP8A/wD/AP////////////////////////////////////////////////////////////////////////////////8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP////////////////////////////////////////////////////////////////////////////////8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP//////////////////////////////////////////////////////////////////////////////////////AP8A//////////////////////////////////////////////////////////////////////////////////////8B/wH/Af8B/wH//////wH/Af8B/wH///////////////////////////////////////////////////////////////////////////////////8B/wH/Af8B/wH//////wH/Af8B/wH/////////////////////////////////////////////////////////////////////////////////Af8B/wH/Af8B/wH//////wH/Af8B/wH/Af8B/wH/Af8B////////////////////////////////////////////////////////////////////Af8B/wH/Af8B/wH///8B/wH/Af8B/wH/Af8B/wH/Af8B/wH/Af8B/wH/////////////////////////////////////////////////////////Af8B/wH/Af8B/wH/Af8B/wH/Af8B/wH/Af8B/wH/Af8B/wH/Af8B/wH/////////////////////////////////////////////////////////Af8B/wH/Af8B/wH/Af8B/wH/Af8B/wH/Af8B/wH/Af8B/wH/Af8B/wH///////////////////////////////////////////////////////////8B/wH/Af8B/wH/Af8B/wH/Af8B/wH/Af8B/wH/Af8B/wH/Af8B/wH///////////////////////////////////////////////////////////8B/wH/Af8B/wH/Af8B/wH/Af8B/wH/Af8B/wH/Af8B/wH/Af8B//////////////////////////////////////////////////////////////8B/wH/Af8B/wH//////wH/Af8B/wH//////////////////////////////////////////////////////////////////////////////////////////////////////wH/Af8B/wH/////////////////////////////////////////////////////////////////////////////////
walls:
  kinds:
    - interior_brick
  entries: AAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8A/wD/AP8A/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8A/wD/AP8A/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8A/wD/AP8A/wAAAf8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8A/wD/AP8A/wAAAf8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8A/wD/AP8A/wAAAf8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8A/wD/AP8A/wAAAf8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8A/wD/AP8A/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A
layer_set:
  tileset/interior_brick_outer_edge_w: ACgAJAAoABoAKAAcACgAHgAoACAAKAAiACgAGAAmABIAJgAEACYABgAmAAgAJgAKACYADAAmAA4AJgAQABQAAgAUAAQAFAAGABQACAAUAAoADAAUAAwAFgAWABYAFgAYAAwAGAAMACQAFgAkAAwAJgAWACYAFgAo
  tileset/interior_brick_outer_edge_e: AAAAJAAAACYAAAAgAAAAIgAAABYAAAAYAAAAGgAAABwAAAAeAAAAFAAAAA4AAAACAAAABAAAAAYAAAAIAAAACgAAAAwAGAAEABgABgAYAAgAGAAKAA4AEgAQABYAGAAYABAAGAAQACQAGAAkABAAJgAQACg=
  tileset/plate05: ACEAJAACAB4=
  tileset/interior_brick_outer_edge_n: AAIAKAAEACgABgAoAAgAKAAKACgAIAAmACIAJgAkACYAJgAmAAIAEAAEABAABgAQAAgAEAAkABQAIAAUACIAFAAeABQAGgAUABwAFAAKABAADAAQABgAFAAcACYAHgAmAA4AIgAaACY=
  tileset/book01: ACEAGg==
  tileset/interior_brick_outer_edge_s: AAIAAAAEAAAABgAAAAIAEgAEABIABgASAAgAEgAIAAAACgAAAAwAAAAOAAAAEAAAABIAAAAkABYAJgAWABoAAgAcAAIAHgACACAAAgAiAAIAJAACACAAFgAiABYAFgAMAAoAEgAaABYAHAAWAB4AFgAOABo=
  tileset/wall_interior_brick_outer_edge_sw: ABQADgAWABwADAAc
  tileset/cabinet_wide04: AAIABw==
  tileset/interior_brick_inner_edge_se: AAAAEgAAAAAAGAACABgAFg==
  tileset/banner_blue: ABYADg==
  props/barrels: ACQAGw==
  tileset/swords02: ABcAHQAPAB0=
  tileset/bar_vert_west_n: AAIAHA==
  tileset/interior_brick_outer_edge_nw: ABYAFAAMACIAFgAi
  tileset/cabinet_top_01: ACEAGg==
  bed_small02: AB0ABw==
  tileset/wall_crack01: AAoABAAJABYAIwAa
  tileset/interior_wood01_base: ABAAJgASACYAFAAmABYAJgAQACgAEgAoABQAKAAWACgAEAAkABIAJAAUACQADgAcABAAHgAQACAAEAAiABIAIgAUACIADAAeAA4AHgAMACIADAAkAA4AJAAIAB4ACgAeAAoAIgAKACQACgAmAAIAIgAEACIABgAiAAgAIgACACQABAAkAAYAJAAIACQAAgAmAAQAJgAIACYAAAAcAAAAHgACAB4ABAAeAAYAHgAAACAAAgAgAAYAIAACABgAAgAaAAIAHAAEABYABgAWAAgAFgAKABYABgAYAAgAGAAKABgABAAaAAYAGgAIABoACgAaAAQAHAAGABwACAAcAAoAHAAYABoAGAAcABIAHgAUAB4AEgAgABQAIAAQABYAEgAWABQAFgAWABYAEAAYABIAGAAUABgAFgAYABAAGgASABoAFAAaABYAGgAQABwAEgAcABQAHAAWABwAFgAeABgAHgAWACAAGAAgABgAIgAWACQAGAAkABoAJAAaABoAHAAaAB4AGgAgABoAIgAcACQAHAAmABwAKAAcACgAHgAoACAAKAAiACQAHgAmAB4AJAAgACQAIgAmACIAJAAkACYAJAAiAB4AIgAgACIAIgAcACQAHgAkACAAJAAiACQAGgAcABwAHAAeABwAIAAcABoAHgAeAB4AIAAeABoAIAAcACAAHgAgACAAIAAaACIAHAAiAB4AIgAgACIAHAAeACYAIAAOACAADAAgAAoAIAAIACAABAAgAAYAJgAEABg=
  tileset/plate08: ABoAJA==
  tileset/cabinet09: AA4AAg==
  tileset/interior_brick_inner_edge_nw: ACgAJgAmABQADAAo
  tileset/wall_interior_brick_outer_edge_s: AAAAFAAAAAIAAgACAAQAAgAGAAIAAgAUAAQAFAAIAAIACgACAAwAAgAOAAIAEAACABIAAgAkABgAJgAYACgAGAAmAAQAFAACABgABAAaAAQAHAAEAB4ABAAgAAQAIgAEACQABAAgABgAIgAYABYADgAGABQACAAUAAoAFAAMABQAGAAYABoAGAAcABgAHgAYAA4AHA==
  props/boxes02: ABwAHQ==
  tileset/bottles01: ABwAJAAlACQ=
  tileset/wall_interior_brick_outer_edge_se: ABgADgAYABwAEAAc
  tileset/meat02: AAoADA==
  props/anvil: AAkAFw==
  tileset/interior_brick_base: ABwAKAAeACgAIAAoACIAKAAkACgAJgAoACgAKAAoABQAKAASACgAEAAoAAAAKAACACgABAAoAAYAKAAIACgACgAoAAwAKAAOACYAAAAWAAAAGAAAABoAAAAcAAAAHgAAACAAAAAiAAAAJAAAABYAAgAWAAQAFgAGABYACAAWAAoADgAWAA4AGAAOACQADgAmAA4AKAAYACgAGgAo
  tileset/interior_brick_outer_edge_ne: AA4AEAAQABQAEAAiABgAIg==
  props/barrel: AB4AGw==
  table_large01: AAoACg==
  tileset/cabinet_bot_01: ACEAHA==
  tileset/bar_horiz_c: ABoAJAAcACQAHgAkACAAJAAiACQAJAAkACYAJA==
  tileset/cabinet07: ABIAAg==
  tileset/interior_stone_base: ABQAFAASABQAEgAQABQAEAASABIAFAASAA4AEAAQABAADgASABAAEgACAAYABAAGAAYABgAIAAYAAgAIAAQACAAGAAgAAgAKAAQACgAGAAoAAgAMAAIADgAIAAgACAAKAAgADAAIAA4ACgAOABIABgASAAgADAAOAA4ADgAQAA4AEgAOAAoABAAMAAQADgAEABAABAAKAAYADAAGAA4ABgAQAAYADgAIABAACAAKAAgADAAIAAQADAAGAAwABAAOAAYADgAKAAoACgAMABAACgASAAoAEAAMABIADAAOAAoADAAMAA4ADAAMAAoAFgAOABgADgAWABAAGAAQABYAEgAYABIAGgAOABoAEAAaABIAHAASAB4ADgAeABIAIAAMACIADAAkAAwAIAAGACIABgAkAAYAIAAIACQACAAgAAoAIgAKACQACgAaAAgAHAAIAB4ACAAaAAoAHAAKAB4ACgAcAAwAHgAMACAADgAiAA4AJAAOACAAEAAiABAAJAAQACAAEgAiABIAJAASAB4AEAAcABAAHAAOABoADAAiAAg=
  01entry_light: ABEAJg==
  tileset/chair03: AAgADQ==
  tileset/interior_brick_inner_edge_sw: ACgAFgAmAAIAFAAAAAwAEg==
  tileset/sack_stack: ABoAGQAcABk=
  armor_statue: AAMAFgAGABY=
  tileset/cabinet_bot_04: AAgAAw==
  tileset/cabinet_small_01: AAgABQ==
  tileset/chair04: AA4ADQAOAAo=
  tileset/plate06: AAwACw==
  tileset/bottles03: AB8AJA==
  bed_small01: ABoABwAgAAcAIwAH
  tileset/bar_vert_west_s: AAIAHg==
  tileset/wine_bottle01: ACMAJA==
  tileset/papers02: AAQACA==
  tileset/cabinet08: ABAAAg==
  tileset/interior_wood01_base_variant1: AA4AIgAAABoAAgAWABYAIg==
  tileset/interior_brick_outer_edge_se: ABgADAAYABoAEAAa
  tileset/barrel_water: ABoAHQ==
  props/target: AAIAJQACACI=
  tileset/interior_brick_inner_edge_ne: AAAAKAAAABAADgAUABgAJg==
  tileset/rug_small01: AAMABg==
  tileset/interior_brick_outer_edge_sw: ABQADAAWABoADAAa
  boxes06: ACMAEA==
  tileset/bucket_full: ACQAEg==
elevation: AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAICAgIAAAAAAAACAgICAgICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAICAgIAAAAAAAACAgICAgICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAICAgIAAAAAAAACAgAAAAAAAAAAAAAAAAAAAAACAgAAAAAAAAAAAAAAAAICAgIAAAAAAAACAgAAAAAAAAAAAAAAAAAAAAACAgAAAAAAAAAAAAAAAAICAgIAAAAAAAACAgAAAAAAAAAAAAAAAAAAAAACAgAAAAAAAAAAAAAAAAICAgIAAAAAAAACAgAAAAAAAAAAAAAAAAAAAAACAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgAAAAAAAAAAAAAAAAICAgIAAAAAAAACAgAAAAAAAAAAAAAAAAAAAAACAgAAAAAAAAAAAAAAAAICAgIAAAAAAAACAgAAAAAAAAAAAAAAAAAAAAACAgAAAAAAAAAAAAAAAAICAgIAAAAAAAACAgAAAAAAAAAAAAAAAAAAAAACAgAAAAAAAAAAAAAAAAICAgIAAAAAAAACAgAAAAAAAAAAAAAAAAAAAAACAgAAAAAAAAAAAAAAAAICAgIAAAAAAAACAgICAgICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAICAgIAAAAAAAACAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAAAAAAAACAgICAgICAgICAgICAgICAgIC