---
id: rose_lake_temple
name: Rose Lake Temple
width: 38
height: 30
visibility_tile: gui/area_invis
explored_tile: gui/area_unexplored
max_vis_distance: 12
max_vis_up_one_distance: 6
world_map_location: rose_lake
default_music: music/theme_grasslands05
on_rest:
  Disabled:
    message: You cannot rest here.  Find an inn or temple.
location_kind: Indoors
layers:
  - terrain_base
  - terrain_border
  - walls
  - walls_top
  - prop
  - object
  - object_interior
  - decoration
  - walls_aerial
  - aerial
  - aerial_prop
entity_layer: 7
actors:
  - id: rose_lake_high_priestess
    location:
      x: 24
      y: 13
    unique_id: ~
props: []
encounters: []
transitions:
  - from:
      x: 16
      y: 27
    size: 4by3
    to:
      Area:
        id: rose_lake
        x: 96
        y: 82
    hover_text: To Outside
    image_display: empty
triggers: []
terrain:
  kinds:
    - interior_tile
  entries: AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP///////////////////////////////////////////////////wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD///////////////////////////////////////////////////8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP///////////////////////////////////////////////////wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD///////////////////////////////////////////////////8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP///////////////////////////////////////////////////wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD///////////////////////////////////////////////////8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP///////////////////////////////////////////////////wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD///////////////////////////////////////////////////8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP///////////////////////////////////////////////////////////wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD///////////////////////////////////////////////////////////8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////
walls:
  kinds:
    - interior_stone_ceil
  entries: AAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8AAAH/AP8A/wD/AP8A/wD/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8AAAH/AP8A/wD/AP8A/wD/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8AAAH/AAAB/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8AAAH/AP8A/wAAAf8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A
layer_set:
  tileset/chair07: AB4ACQ==
  tileset/interior_stone_ceil_outer_edge_nw: ACIAEAAUABo=
  tileset/interior_stone_ceil_base: AAAAHAACABwABAAcAAYAHAAIABwAAAAaAAIAGgAAABgAAgAYAAAAFgACABYAAAAUAAIAFAAAABIAAgASAAAAEAACABAAAAAOAAIADgAAAAAAAAACAAAABAAAAAYAAAAIAAAACgAAAAwAAgAAAAIAAgACAAQAAgAGAAIACAACAAoAAgAMAAoAHAAMABwABAAaAAYAGgAIABoACgAaAAwAGgAEAAAABgAAAAgAAAAKAAAADAAAAA4AAAAQAAAAEgAAABQAAAAWAAAAGAAAABoAAAAcAAAAHgAAACAAAAAiAAAAFgAcABgAHAAaABwAHAAcAB4AHAAgABwAIgAcACQAAAAkABw=
  tileset/window10: ACAAAw==
  tileset/cabinet_top_02: AAgAFgAiABg=
  tileset/cabinet_med02: ACIABQ==
  table_large01: ABYACA==
  tileset/interior_stone_ceil_outer_edge_w: ABoABAAaAAYAGgAIABoACgAaAAwAGgAOABoAEAAUABwAJAAOACQADAAkAAoAJAAIACQABgAkAAQAJAAYACQAFgAkABQ=
  tileset/wall_interior_plaster_outer_edge_s: AAQABAAGAAQACAAEAAoABAAMAAQADgAEABAABAASAAQAFAAEABYABAAYAAQAGgAEABwABAAeAAQAIAAEACIABAAkAAQAHAAUACQAFA==
  tileset/interior_stone_ceil_outer_edge_ne: AB4AEAAOABg=
  bench_n: AAgAEgAMABIAEAASAAgADgAMAA4AEAAO
  tileset/interior_stone_ceil_outer_edge_se: AB4AEg==
  tileset/bar_horiz_e: AAoACQ==
  tileset/interior_stone_ceil_inner_edge_nw: ACQAEAAkABo=
  tileset/interior_stone_ceil_inner_edge_ne: AAQAGAAcABA=
  tileset/interior_stone_ceil_inner_edge_sw: ABoAAgAkAAIAJAAS
  tileset/interior_tile_base_variant1: AA4AHAAAAAYAAAAIAAIAAAAIAAQADAAEAA4AAgAUAAAAIgAAABoAAgAUAAQAFgAEABgABAAaAAwAGgAOACIAFAAkABgAGAAaACIAGgAcABw=
  tileset/wall_interior_plaster_outer_edge_se: AB4AFA==
  tileset/interior_stone_ceil_outer_edge_e: AAQAFgAEABQABAASAAQAEAAEAAQABAAGAAQACAAEAAoABAAMAAQADgAkAAIAHAAEABwABgAcAAgAHAAKABwADAAcAA4AJAAQAA4AGgAOABwAJAASACQAGg==
  tileset/window19: ABYABAAIAAQAEAAE
  tileset/cabinet_top_03: AAYAFg==
  tileset/interior_stone_ceil_outer_edge_s: AAYAAgAIAAIACgACAAwAAgAOAAIAEAACABIAAgAUAAIAFgACABgAAgAeAAIAIAACACIAAgAcABI=
  tileset/table01: AB4ADg==
  tileset/cabinet_wide04: AB4ABQ==
  tileset/bar_horiz_c: AAwACQAOAAk=
  01entry_light: AA8AGg==
  tileset/bar_horiz_w: ABAACQ==
  tileset/wall_interior_plaster_outer_edge_sw: ABoAFAAiABQ=
  tileset/book01: ACAABg==
  tileset/cabinet_top_04: AAoAFgAMABY=
  tileset/interior_tile_base: ABIAEgASABQAEgAWABIAGAAGABoACAAaAAoAGgAMABoADgAaABAAGgASABoABgAcAAgAHAAKABwADAAcABAAHAASABwADgASABAAEgAOABQAEAAUAA4AFgAQABYAAAAYAAIAGAAEABgABgAYAAgAGAAKABgADAAYAA4AGAAQABgADAASAAwAFAAAABYAAgAWAAQAFgAGABYACAAWAAoAFgAMABYAAAAUAAIAFAAEABQABgAUAAgAFAAKABQAAAASAAIAEgAEABIACgASAAAAAAAAAAIAAAAEAAAACgAAAAwAAAAOAAAAEAAEAAAAAgACAAQAAgACAAQABAAEAAIABgAEAAYAAgAIAAQACAACAAoABAAKAAIADAAEAAwAAgAOAAQADgACABAABAAQAAYAAAAGAAIABgAEAAYABgAGAAgABgAKAAYADAAGAA4ABgAQAAgAAAAIAAIACAAGAAgACAAIAAoACAAMAAgADgAIABAACgAAAAoAAgAKAAQACgAGAAoACAAKAAoACgAMAAoADgAKABAADAAAAAwAAgAMAAYADAAIAAwACgAMAAwADAAQAA4AAAAOAAQADgAGAA4ACAAOAAoADgAMAA4ADgAQAAAAEAACABAABAAQAAYAEAAKABAADAAQAA4AEgAAABIAAgASAAQAEgAGABIACgASAAwAEgAOABYAAAAYAAAAGgAAABwAAAAeAAAAIAAAACQAAAAUAAIAFgACABgAAgAcAAIAHgACACAAAgAiAAIAJAACABoABAAcAAQAHgAEACAABAAiAAQAJAAEABQABgAWAAYAGAAGABoABgAcAAYAHgAGACAABgAiAAYAJAAGABQACAAWAAgAGAAIABoACAAcAAgAIAAIACIACAAkAAgAFgAKABgACgAaAAoAHAAKACAACgAiAAoAJAAKABQADAAWAAwAGAAMABwADAAgAAwAIgAMACQADAAUAA4AFgAOABgADgAcAA4AHgAOACAADgAiAA4AJAAOABQAEAAWABAAGAAQABoAEAAcABAAHgAQACAAEAAiABAAJAAQABQAEgAYABIAGgASABwAEgAeABIAIAASACIAEgAkABIAGAAUABoAFAAcABQAHgAUACAAFAAkABQAFgAWABgAFgAaABYAHAAWAB4AFgAgABYAIgAWACQAFgAUABgAFgAYABgAGAAaABgAHAAYACIAGAAUABoAFgAaABoAGgAcABoAHgAaACAAGgAkABoAFAAcABYAHAAYABwAGgAcAB4AHAAgABwAIgAcACQAHAASAAgAEAAIABQACgAeAAgAHgAKAB4ADAAMAA4ADgAQABAAEAASABAAFgASABYAFAAUABQAFAAWAAYAEgAIABIAIAAYAB4AGA==
  tileset/interior_stone_ceil_outer_edge_n: AAYAGAAIABgACgAYAAwAGAAWABoAGAAaABoAGgAcABoAHgAaACAAGgAiABo=
  tileset/lantern_off: AB4ADg==
  tileset/wine_bottle02: ABcACg==
  tileset/interior_stone_ceil_inner_edge_se: AAQAAgAcAAI=
  tileset/interior_stone_ceil_outer_edge_sw: ABoAEgAiABI=
elevation: AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgIAAAAAAAAAAAICAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgAAAAAAAAAAAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAAAAAAAAAAACAgICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgIAAAAAAAAAAAICAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgAAAAAAAAAAAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAAAAAAAAAAACAgICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgIAAAAAAAAAAAICAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgAAAAAAAAAAAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAAAAAAAAAAACAgICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgIAAAAAAAAAAAICAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgAAAAAAAAAAAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAAAAAAAAAAACAgICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgIAAAAAAAAAAAICAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgAAAAAAAAAAAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgIAAAAAAgICAgICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgAAAAACAgICAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgICAgICAgICAgICAAAAAAAAAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAAAAAAAACAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgAAAAAAAAICAgICAgICAgICAgICAgIC