---
id: rose_lake_town_hall
name: Rose Lake Town Hall
width: 48
height: 40
visibility_tile: gui/area_invis
explored_tile: gui/area_unexplored
max_vis_distance: 12
max_vis_up_one_distance: 6
world_map_location: rose_lake
on_rest:
  Disabled:
    message: You cannot rest here.  Find an inn or temple.
location_kind: Indoors
generate: false
layers:
  - terrain_base
  - terrain_border
  - walls
  - walls_top
  - prop
  - object
  - object_interior
  - decoration
  - walls_aerial
  - aerial
  - aerial_prop
entity_layer: 7
actors:
  - id: townsperson01
    location:
      x: 35
      y: 24
    unique_id: rlth_01
  - id: townsperson03
    location:
      x: 38
      y: 25
    unique_id: rlth_02
  - id: townsperson02
    location:
      x: 37
      y: 8
    unique_id: rlth_03
  - id: townsperson07
    location:
      x: 4
      y: 22
    unique_id: rlth_04
  - id: townsperson10
    location:
      x: 24
      y: 16
    unique_id: rlth_05
  - id: townsperson15
    location:
      x: 22
      y: 13
    unique_id: rlth_06
  - id: townsperson13
    location:
      x: 9
      y: 19
    unique_id: rlth_07
  - id: noble04
    location:
      x: 8
      y: 9
    unique_id: rlth_08
  - id: noble05
    location:
      x: 11
      y: 8
    unique_id: rlth_09
props: []
encounters: []
transitions:
  - from:
      x: 20
      y: 37
    size: 4by3
    to:
      Area:
        id: rose_lake
        x: 57
        y: 66
    hover_text: To Rose Lake
    image_display: empty
triggers: []
terrain:
  kinds:
    - interior_wood02
    - fancy_carpet
  entries: //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////8A/wD/AP8A/wD/AP8A/wD/AP8A/wD///////////////////////////////////////////////////////////////////////////////////////////////////8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A//////////////////////////////////////////////////////////////////////8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////////////////////AP8A/wD/AP8B/wH/Af8B/wH/Af8B/wD/AP8A/wD/AP8A/wD/Af8B/wH/Af8A////////////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A//////////////////////////////////////////////////////////////////////////////8A/wD/AP8A/wD/AP8A/wD/AP8A/wD///////////////////////////////////////////////////////////////////////////////////////////////////8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/////////////////////////////////////////////////////////////////////////////////////////
walls:
  kinds:
    - interior_stone_ceil
  entries: AAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A
layer_set:
  table_large01: AAoAGAAFAA8AFwAK
  tileset/interior_wood02_base_variant1: AAgAJAAKACYAFAAmAAAACAAEAAQAFgAEACAABAAkAAQAIAAKACAAEAAgABYAIAAYAB4AHAAgAB4AHgAgACgAIAAgACIAKgAiAA4AIg==
  tileset/gravel_outer_edge_w: AC4AAAAuAAIALgAEAC4ABgAuAAgALgAKAC4ADAAuAA4ALgAQ
  tileset/barrel_water: ACIAGwAkABs=
  tileset/interior_stone_ceil_inner_edge_sw: AB4AAAAuAAA=
  tileset/fancy_carpet_base: AAgACAAOAAgADAAIAAoACAAQAAgAFAAIABIACAAkAAgAJgAIACgACAAqAAg=
  tileset/wall_interior_plaster_outer_edge_s: ABQAAgAWAAIAAAACAAIAAgAEAAIABgACAAgAAgAKAAIADAACAA4AAgAQAAIAEgACABgAAgAaAAIAHAACAB4AAgAgAAIAIgACACQAAgAmAAIALgAkACgAAgAqAAIALAACAC4AAg==
  props/vase: ABgAHQARAB0=
  tileset/wall_interior_plaster_outer_edge_sw: AB4ADg==
  tileset/grass_dead_outer_edge_w: AC4AEgAuABQALgAWAC4AGAAuABoALgAiAC4AJAAuACYALgAcAC4AHgAuACA=
  tileset/cabinet05: AAoAAgAUAAI=
  tileset/interior_stone_ceil_outer_edge_se: ACAADAAuACY=
  tileset/interior_stone_ceil_inner_edge_se: AAAAAAAgAAAALgAi
  tileset/gravel_outer_edge_sw: AC4AEg==
  tileset/fancy_carpet_outer_edge_se: ABYACgAsAAo=
  tileset/fancy_carpet_outer_edge_s: AAgACgAKAAoADAAKAA4ACgAQAAoAEgAKABQACgAkAAoAJgAKACgACgAqAAo=
  tileset/cabinet06: ABYAAg==
  tileset/cabinet03: AAYAAg==
  tileset/chair03: AAIAEgACABAAAgAOAAcAHAAHABk=
  tileset/chair04: ABsACgAbAA0ADgAYAA4AGw==
  tileset/cabinet07: AAgAAg==
  tileset/sack_stack: ACIAHQAkAB0AJgAd
  tileset/interior_stone_ceil_inner_edge_ne: AAAAIAAgACA=
  tileset/cabinet02: ABgAAg==
  tileset/fancy_carpet_outer_edge_e: ABYACAAsAAg=
  tileset/interior_stone_ceil_outer_edge_w: ABgAJgAeAAIAHgAEAB4ABgAeAAgAHgAKABgAIgAYACQAHgAeAB4AFgAeABgAHgAaAB4AHAAuABYALgAYAC4AGgAuABwALgAeAC4AFAAuABAALgASAC4ADgAuAAoALgAMAC4AAgAuAAQALgAGAC4ACA==
  tileset/cabinet_med02: ACYAAwAoAAM=
  tileset/interior_stone_ceil_inner_edge_nw: AB4AIAAuACA=
  tileset/bucket_full: AAIABQ==
  props/barrels: ACgAHQACABwAAgAY
  tileset/interior_stone_ceil_outer_edge_nw: ABgAIAAeABQ=
  tileset/wall_interior_plaster_outer_edge_se: ACAADg==
  tileset/interior_stone_ceil_outer_edge_n: AAIAIAAEACAABgAgAAgAIAAKACAADAAgAA4AIAAQACAAGgAgABwAIAAiACAAJAAgACYAIAAoACAAKgAgACwAIA==
  tileset/interior_stone_ceil_outer_edge_e: ABIAJgAAAB4AEgAiABIAJAAAABgAAAAaAAAAHAAAABYAAAAUAAAAAgAAAAQAAAAGAAAACAAAAAoAAAAMAAAADgAAABAAAAASACAAAgAgAAQAIAAGACAACAAgAAoAIAAeACAAFgAgABgAIAAaACAAHAAuACQ=
  tileset/interior_stone_ceil_outer_edge_ne: ABIAIAAgABQ=
  tileset/interior_stone_ceil_base: AAAAJgACACYABAAmAAYAJgAIACYACgAmAAwAJgAeACYAIAAmACIAJgAkACYAJgAmAA4AJgAQACYAGgAmABwAJgAAACIAAgAiAAQAIgAGACIACAAiAAoAIgAMACIADgAiABAAIgAAACQAAgAkAAQAJAAGACQACAAkAAoAJAAMACQADgAkABAAJAAaACIAHAAiAB4AIgAgACIAIgAiACQAIgAmACIAGgAkABwAJAAeACQAIAAkACIAJAAkACQAJgAkACgAIgAqACIALAAiACgAJAAqACQALAAk
  tileset/window19: ABoAAgAEAAI=
  tileset/fancy_carpet_outer_edge_nw: AAYABgAiAAY=
  01entry_light: ABMAJA==
  tileset/interior_stone_ceil_outer_edge_s: ABQAAAAWAAAAAgAAAAQAAAAGAAAACAAAAAoAAAAMAAAADgAAABAAAAASAAAAGAAAABoAAAAcAAAAIgAAACQAAAAmAAAAJgAmACQAJgAoACYAKgAmACwAJgAoAAAAKgAAACwAAA==
  tileset/chair02: AAsAHQAGABQ=
  tileset/interior_stone_ceil_outer_edge_sw: AB4ADA==
  tileset/interior_wood02_base: AAoAJAAMACQADgAkABAAJAASACQAFgAkABgAJAAaACQAHAAkAAgAJgAMACYADgAmABAAJgASACYAFgAmABgAJgAaACYAHAAmABYAGgAWABwAFgAeABYAIAAWACIAAAAKAAAADAACAAIABAACAAYAAgAIAAIACgACAAwAAgAOAAIAEAACABIAAgAUAAIAFgACAAIABAAGAAQACAAEAAoABAACAAYABAAGAAYABgAIAAYACgAGAAIACAAEAAgABgAIAAIACgAEAAoABgAKAAgACgAKAAoAAgAMAAQADAAGAAwACAAMAAoADAAMAAQADgAEABAABAASAAQAFAAEAA4ABgAQAAYAEgAGABQABgAWAAYAFgAIAAwACgAOAAoAEAAKABQACgAWAAoADAAMAA4ADAAQAAwAEgAMABYADgAWABAAFgASABYAFAAWABYAFgAYABgABAAaAAQAHAAEAB4ABAAiAAQAJgAEACgABAAqAAQALAAEABgABgAaAAYAHAAGAB4ABgAgAAYAIgAGACQABgAoAAYAKgAGACwABgAYAAgAHAAIAB4ACAAgAAgAIgAIACwACAAYAAoAGgAKABwACgAeAAoAIgAKACQACgAmAAoAKAAKACoACgAsAAoAGAAMABoADAAcAAwAHgAMACAADAAiAAwAJAAMACYADAAoAAwAKgAMACwADAAYAA4AHgAOACAADgAiAA4AJAAOACYADgAoAA4AKgAOABgAEAAaABAAHAAQAB4AEAAiABAAJAAQACgAEAAqABAALAAQABgAEgAaABIAHAASAB4AEgAgABIAIgASACQAEgAmABIAKAASACoAEgAsABIAGAAUABoAFAAcABQAHgAUACAAFAAiABQAJAAUACoAFAAsABQAGAAWABoAFgAcABYAHgAWACIAFgAkABYAJgAWACoAFgAsABYAGAAYABoAGAAcABgAHgAYACIAGAAmABgAKAAYACoAGAAsABgAGAAaABoAGgAcABoAHgAaACAAGgAiABoAJAAaACYAGgAoABoAKgAaACwAGgAYABwAGgAcABwAHAAgABwAIgAcACQAHAAmABwAKAAcACoAHAAsABwAGAAeABwAHgAeAB4AIgAeACQAHgAmAB4AKAAeACoAHgAYACAAGgAgABwAIAAgACAAIgAgACQAIAAmACAAKgAgACwAIAAYACIAGgAiABwAIgAeACIAIgAiACQAIgAmACIAKAAiACwAIgAAAA4AAgAOAAQADgAGAA4ACAAOAAoADgAMAA4ADgAOABAADgASAA4AFAAOAAAAEAACABAABAAQAAYAEAAIABAACgAQAAwAEAAOABAAEAAQABIAEAAUABAAAAASAAIAEgAEABIABgASAAgAEgAKABIADAASAA4AEgAQABIAEgASABQAEgAAABQAAgAUAAQAFAAGABQACAAUAAwAFAAOABQAEgAUABQAFAAAABYAAgAWAAQAFgAGABYACAAWAAoAFgAMABYADgAWABIAFgAAABgAAgAYAAQAGAAGABgACAAYAAoAGAAMABgADgAYABAAGAASABgAFAAYAAAAGgACABoACAAaAAoAGgAMABoADgAaABAAGgASABoAFAAaAAAAHAAEABwABgAcAAgAHAAKABwADgAcABAAHAASABwAFAAcAAAAHgACAB4ABAAeAAYAHgAIAB4ACgAeAAwAHgAOAB4AEAAeABIAHgAUAB4AAAAgAAIAIAAEACAABgAgAAgAIAAKACAADAAgAA4AIAAQACAAEgAgABQAIAAAACIAAgAiAAQAIgAGACIACAAiAAoAIgAMACIAEAAiABIAIgAUACIAAgAcAAwAHAAaAB4AFAAkAAQAGgAGABoACgAUABAAFAAQABYAFAAWABwADgAaAA4AFgAMABQADAASAAoADAAGABoACAAsAA4AJgAQACgAFAAmABQAKAAWACQAGAAsAB4AJgAG
  tileset/fancy_carpet_outer_edge_w: AAYACAAiAAg=
  tileset/fancy_carpet_outer_edge_n: AAgABgAKAAYADAAGAA4ABgAQAAYAEgAGABQABgAkAAYAJgAGACgABgAqAAY=
  tileset/fancy_carpet_outer_edge_sw: AAYACgAiAAo=
  tileset/fancy_carpet_outer_edge_ne: ABYABgAsAAY=
  tileset/window09: ACoAAgAkAAI=
elevation: AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgIAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgIAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgIAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgIAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgIAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgIAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgIAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgIAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgIAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgIAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgIAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgIAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgIAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgIAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgIAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgIAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgIAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgIAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgIAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgIAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgIAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgIAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgIAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgIAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgIAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgIAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgIAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgIAAAAAAAAAAAAAAgICAgICAgICAgICAgICAgICAgICAgAAAAAAAAICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgAAAAAAAAICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgAAAAAAAAICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgAAAAAAAAICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgAAAAAAAAICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgAAAAAAAAICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgAAAAAAAAICAgICAgICAgICAgICAgICAgICAgIC