---
id: wellswood_town_hall
name: Wellswood Town Hall
width: 42
height: 38
visibility_tile: gui/area_invis
explored_tile: gui/area_unexplored
max_vis_distance: 20
max_vis_up_one_distance: 6
world_map_location: wellswood
on_rest:
  Disabled:
    message: You cannot rest here.  Find an inn or temple.
location_kind: Indoors
generate: false
layers:
  - terrain_base
  - terrain_border
  - walls
  - walls_top
  - prop
  - object
  - object_interior
  - decoration
  - walls_aerial
  - aerial
  - aerial_prop
entity_layer: 7
actors:
  - id: townsperson16
    location:
      x: 35
      y: 23
    unique_id: ~
  - id: townsperson17
    location:
      x: 21
      y: 23
    unique_id: ~
  - id: townsperson18
    location:
      x: 28
      y: 18
    unique_id: ~
  - id: townsperson19
    location:
      x: 29
      y: 22
    unique_id: ~
  - id: mayor_fenk
    location:
      x: 29
      y: 9
    unique_id: ~
  - id: npc_jhilsara
    location:
      x: 19
      y: 6
    unique_id: ~
props: []
encounters: []
transitions:
  - from:
      x: 16
      y: 33
    size: 4by3
    to:
      Area:
        id: wellswood
        x: 101
        y: 33
    hover_text: To Outside
    image_display: empty
triggers: []
terrain:
  kinds:
    - interior_dirt
  entries: AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A////////////////////////////////////////////////////////////
walls:
  kinds:
    - interior_stone_ceil
    - interior_brick
  entries: AAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wABAf8AAQH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wABAf8AAQH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AAEB/wABAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAQH/AAEB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AAEB/wABAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAQH/AAEB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A
layer_set:
  tileset/wall_interior_plaster_outer_edge_se: AAoADgAQAAY=
  tileset/interior_brick_outer_edge_ne: ABIADgAKABoAGgAa
  tileset/interior_brick_outer_edge_nw: ABAADgAIABoAGAAa
  tileset/interior_stone_ceil_outer_edge_s: ABgAAAAaAAAAAgAAAAQAAAAGAAAACAAAAAoAAAAMAAAAEgAAABQAAAAWAAAAHAAAAAIADAAEAAwABgAMAAgADAAeAAAAIAAAACIAAAAkAAAAJgAA
  tileset/wall_interior_plaster_outer_edge_s: ABgAAgAaAAIAHAACAAAADgACAA4ABAAOAAYADgAIAA4AAgACAAQAAgAGAAIACAACAAoAAgAMAAIADgACABAAAgASAAIAFAACABYAAgAeAAIAIAACACIAAgAkAAIAJgACACgAAg==
  tileset/chair03: ABYAFQAWABI=
  tileset/bar_horiz_e: ABsACw==
  tileset/wine_bottle02: AAMAEg==
  tileset/interior_stone_ceil_outer_edge_ne: AAoACgAAACQ=
  tileset/interior_stone_ceil_inner_edge_se: AAAAAAAQAAAAAAAM
  tileset/interior_dirt_base: ACAAGAAiABgAJAAYACYAGAAgABoAIgAaACQAGgAmABoAIAAcACIAHAAkABwAJgAcACAAHgAiAB4AJAAeACYAHgAgACAAIgAgACQAIAAmACAAIAAiACIAIgAkACIAJgAiACAAJAAiACQAJAAkACYAJAAaABgAHAAYAB4AGAAaABoAHAAaAB4AGgAaABwAHAAcAB4AHAAaAB4AHAAeAB4AHgAaACAAHAAgAB4AIAAaACIAHAAiAB4AIgAaACQAHAAkAB4AJAAAABgAAgAYAAQAGAAGABgACAAYAAoAGAAMABgADgAYABAAGAASABgAFAAYABYAGAAYABgAAAAaAAIAGgAEABoABgAaAAgAGgAKABoADAAaAA4AGgAQABoAEgAaABQAGgAWABoAGAAaAAAAHAACABwABAAcAAYAHAAIABwACgAcAAwAHAAOABwAEAAcABIAHAAUABwAFgAcABgAHAAAAB4AAgAeAAQAHgAGAB4ACAAeAAoAHgAMAB4ADgAeABAAHgASAB4AFAAeABYAHgAYAB4AAAAgAAIAIAAEACAABgAgAAgAIAAKACAADAAgAA4AIAAQACAAEgAgABQAIAAWACAAGAAgAAAAIgACACIABAAiAAYAIgAIACIACgAiAAwAIgAOACIAEAAiABIAIgAUACIAFgAiABgAIgAAACQAAgAkAAQAJAAGACQACAAkAAoAJAAMACQADgAkABAAJAASACQAFAAkABYAJAAYACQAAAAAAAIAAAAEAAAABgAAAAgAAAAKAAAADAAAAAAAAgACAAIABAACAAYAAgAIAAIACgACAAwAAgAAAAQAAgAEAAQABAAGAAQACAAEAAoABAAMAAQAAAAGAAIABgAEAAYABgAGAAgABgAKAAYADAAGAAAACAACAAgABAAIAAYACAAIAAgACgAIAAwACAAAAAoAAgAKAAQACgAGAAoACAAKAAoACgAMAAoAAAAMAAIADAAEAAwABgAMAAgADAAKAAwADAAMAAAADgACAA4ABAAOAAYADgAIAA4ACgAOAAwADgAAABAAAgAQAAQAEAAGABAACAAQAAoAEAAMABAAAAASAAIAEgAEABIABgASAAgAEgAKABIADAASAAAAFAACABQABAAUAAYAFAAIABQACgAUAAwAFAAAABYAAgAWAAQAFgAGABYACAAWAAoAFgAMABYADgAAABAAAAASAAAAFAAAABYAAAAYAAAAGgAAABwAAAAeAAAAIAAAACIAAAAkAAAAJgAAAA4AAgAQAAIAEgACABQAAgAWAAIAGAACABoAAgAcAAIAHgACACAAAgAiAAIAJAACACYAAgAOAAQAEAAEABIABAAUAAQAFgAEABgABAAaAAQAHAAEAB4ABAAgAAQAIgAEACQABAAmAAQADgAGABAABgASAAYAFAAGABYABgAYAAYAGgAGABwABgAeAAYAIAAGACIABgAkAAYAJgAGAA4ACAAQAAgAEgAIABQACAAWAAgAGAAIABoACAAcAAgAHgAIACAACAAiAAgAJAAIACYACAAOAAoAEAAKABIACgAUAAoAFgAKABgACgAaAAoAHAAKAB4ACgAgAAoAIgAKACQACgAmAAoADgAMABAADAASAAwAFAAMABYADAAYAAwAGgAMABwADAAeAAwAIAAMACIADAAkAAwAJgAMAA4ADgAQAA4AEgAOABQADgAWAA4AGAAOABoADgAcAA4AHgAOACAADgAiAA4AJAAOACYADgAOABAAEAAQABIAEAAUABAAFgAQABgAEAAaABAAHAAQAB4AEAAgABAAIgAQACQAEAAmABAADgASABAAEgASABIAFAASABYAEgAYABIAGgASABwAEgAeABIAIAASACIAEgAkABIAJgASAA4AFAAQABQAEgAUABQAFAAWABQAGAAUABoAFAAcABQAHgAUACAAFAAiABQAJAAUACYAFAAOABYAEAAWABIAFgAUABYAFgAWABgAFgAaABYAHAAWAB4AFgAgABYAIgAWACQAFgAmABY=
  tileset/bucket_full: AAMACA==
  tileset/wall_interior_plaster_outer_edge_sw: AA4ABg==
  tileset/book01: ABwACw==
  tileset/chair04: ACQAFQAkABI=
  tileset/cabinet05: AAgAAg==
  tileset/interior_stone_ceil_outer_edge_e: AAAAAgAAAAQAAAAGAAAACAAQAAIAAAAWAAAAFAAAABIAAAAQAAAADgAAACQAAAAYAAAAGgAAABwAAAAeAAAAIAAAACI=
  tileset/interior_brick_outer_edge_sw: ABAAEAAIABwAGAAc
  tileset/cabinet02: AB4AAgAgAAIAIgACACQAAg==
  tileset/chair02: ACEAFwAZABc=
  tileset/interior_stone_ceil_outer_edge_sw: AA4ABA==
  tileset/chair06: AAIAFgACABkAAgAe
  tileset/bar_horiz_w: AB8ACw==
  tileset/cabinet08: AAYAAg==
  tileset/ropes01: AAkAEA==
  tileset/interior_stone_ceil_outer_edge_se: ABAABAAKAAw=
  tileset/wall_interior_brick_outer_edge_sw: ABAAEgAIAB4AGAAe
  tileset/wall_interior_brick_outer_edge_se: ABIAEgAKAB4AGgAe
  tileset/bottles03: AAwABQ==
  tileset/interior_stone_ceil_inner_edge_nw: ACgAJA==
  01entry_light: AA8AIA==
  tileset/table03: AAMAIQADABwAAwAT
  tileset/papers: ABkAFA==
  tileset/rug_small01: ABEAIg==
  table_large01: ABgAEgAgABI=
  tileset/cabinet07: AAQAAg==
  tileset/chair05: AAYAEg==
  tileset/bar_horiz_c: AB0ACw==
  tileset/cabinet06: AAIAAgAKAAI=
  tileset/interior_stone_ceil_inner_edge_ne: AAAACgAAACQ=
  tileset/interior_stone_ceil_outer_edge_n: AAIACgAEAAoABgAKAAgACgACACQABAAkAAYAJAAIACQACgAkAAwAJAAOACQAEAAkABIAJAAUACQAFgAkABgAJAAaACQAHAAkAB4AJAAgACQAIgAkACQAJAAmACQ=
  tileset/interior_stone_ceil_outer_edge_w: AA4AAgAoAAIAKAAEACgABgAoAAgAKAAKACgADAAoAA4AKAAQACgAEgAoABQAKAAWACgAGAAoABoAKAAiACgAHAAoAB4AKAAg
  tileset/interior_stone_ceil_inner_edge_sw: AA4AAAAoAAA=
  tileset/interior_brick_outer_edge_se: ABIAEAAKABwAGgAc
elevation: AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAACAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAACAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAACAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAACAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgAAAAAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgAAAAAAAAACAgICAAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAAAAAAAICAgAAAAAAAAACAgICAAAAAAAAAAAAAAAAAgICAAAAAAAAAAAAAAAAAAICAgAAAAAAAAACAgICAAAAAAAAAAAAAAAAAgICAAAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC