[package]
name = "sulis_rules"
version = "0.2.0"
authors = ["Jared Stephen <grok_moo@yahoo.com>"]
edition = "2018"

[dependencies]
sulis_core = { path = "../sulis_core" }

rand = "0.5"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
