[package]
name = "sulis_core"
version = "0.2.2"
authors = ["Jared Stephen <grok_moo@yahoo.com>"]
edition = "2018"

[dependencies]
dirs = "1.0"
backtrace = "0.3"
flexi_logger = "0.10"
image = "0.20"
glium = "0.22"
lazy_static = "1.0"
log = "0.4"
rand = "0.6"
rand_pcg = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
serde_json = "1.0"
