[package]
name = "sulis_core"
version = "0.1.1"
authors = ["Jared Stephen <grok_moo@yahoo.com>"]

[dependencies]
backtrace = "0.3"
flexi_logger = "0.9"
image = "0.19"
glium = "0.22"
lazy_static = "1.0"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
serde_json = "1.0"
