[package]
name = "sulis_state"
version = "0.1.0"
authors = ["Jared Stephen <grok_moo@yahoo.com>"]

[dependencies]
sulis_engine = { path = "../sulis_engine" }
sulis_module = { path = "../sulis_module" }
sulis_rules = { path = "../sulis_rules" }

log = "0.4"