[package]
name = "sulis_view"
version = "0.1.1"
authors = ["Jared Stephen <grok_moo@yahoo.com>"]

[dependencies]
sulis_core = { path = "../sulis_core" }
sulis_rules = { path = "../sulis_rules" }
sulis_module = { path = "../sulis_module" }
sulis_state = { path = "../sulis_state" }
sulis_widgets = { path = "../sulis_widgets" }

log = "0.4"
chrono = "0.4"
