[package]
name = "sulis_view"
version = "0.1.0"
authors = ["Jared Stephen <grok_moo@yahoo.com>"]

[dependencies]
sulis_engine = { path = "../sulis_engine" }
sulis_rules = { path = "../sulis_rules" }
sulis_module = { path = "../sulis_module" }
sulis_state = { path = "../sulis_state" }

log = "0.4"
