[package]
name = "sulis_module"
version = "0.3.1"
authors = ["Jared Stephen <grok_moo@yahoo.com>"]
edition = "2018"

[dependencies]
sulis_core = { path = "../sulis_core" }

log = "0.4"
serde = "1.0"
serde_derive = "1.0"
base64 = "0.11"
indexmap = "1.0"
