[package]
name = "sulis_module"
version = "0.5.0"
authors = ["Jared Stephen <grok_moo@yahoo.com>"]
edition = "2018"

[dependencies]
sulis_core = { path = "../sulis_core" }

log = "0.4"
serde = "1"
serde_derive = "1"
base64 = "0.12"
indexmap = "1"
