[package]
name = "sulis_module"
version = "0.1.0"
authors = ["Jared Stephen <grok_moo@yahoo.com>"]

[dependencies]
sulis_engine = { path = "../sulis_engine" }
sulis_rules = { path = "../sulis_rules" }

log = "0.4"
serde = "1.0"
serde_derive = "1.0"
