---
id: rose_lake_gatehouse
name: Rose Lake Gatehouse
width: 44
height: 36
visibility_tile: gui/area_invis
explored_tile: gui/area_unexplored
max_vis_distance: 16
max_vis_up_one_distance: 6
world_map_location: rose_lake
ambient_sound: ~
default_music: ~
default_combat_music: ~
on_rest:
  Disabled:
    message: "<PLACEHOLDER>"
location_kind: Indoors
layers:
  - terrain_base
  - terrain_border
  - walls
  - walls_top
  - prop
  - object
  - object_interior
  - decoration
  - walls_aerial
  - aerial
  - aerial_prop
entity_layer: 7
actors: []
props:
  - id: lever
    location:
      x: 37
      y: 14
    enabled: true
encounters:
  - id: invictans_level16
    location:
      x: 14
      y: 10
    size:
      width: 12
      height: 12
transitions:
  - from:
      x: 13
      y: 25
    size: 4by3
    to:
      Area:
        id: rose_lake
        x: 119
        y: 73
    hover_text: To Outside
    image_display: empty
triggers: []
terrain:
  kinds:
    - interior_wood02
    - fancy_carpet
    - stone_bordered
  entries: //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////8A/wD/AP8A//////////////////////////////////////////////////////////////////////8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP//////////////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD//////////////////////////////////////////////////////////////////////wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8B/wH/AP8A//////////////////////////////////////////////////////////////////////8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/Af8B/wD/AP//////////////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wH/Af8A/wD//////////////////////////////////////////////////////////////////////wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8B/wH/AP8A//////////////////////////////////////////////////////////////////////8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/Af8B/wD/AP//////////////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wH/Af8A/wD//////////////////////////////////////////////////////////////////////wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A//////////////////////////////////////////////////////////////////////8A/wD/AP8A/wL/Av8C/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP//////////////////////////////////////////////////////////////////////AP8A/wD/AP//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
walls:
  kinds:
    - interior_brick
  entries: AAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAAAf8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A
layer_set:
  tileset/stone_bordered_outer_edge_n: AAwAGAAOABgAEAAY
  tileset/bar_vert_west_n: ABwAFA==
  tileset/wall_interior_brick_outer_edge_se: ACoAIA==
  tileset/stone_bordered_outer_edge_w: AAoAGg==
  tileset/cabinet_top_04: ACAAGg==
  tileset/interior_brick_inner_edge_nw: ACgAHA==
  tileset/stone_bordered_outer_edge_se: ABIAHA==
  tileset/interior_brick_outer_edge_s: AAAAHgACAB4ABAAeAAYAHgAIAB4ACgAeAAwAHgAOAB4AEAAeABIAHgAUAB4AFgAeABgAHgAaAB4AHAAeAAQAAgAGAAIACAACAAoAAgAMAAIADgACABAAAgASAAIAFAACABYAAgAYAAIAGgACABwAAgAeAAIAIAACACIAAgAkAAIAJgACAB4AHgAgAB4AIgAeACQAHgAmAB4AKAAe
  tileset/interior_brick_base: AAAAEAAAAA4AAAAMAAAACgAAAAAAAAACAAAABAAAAAYAAAAIAAAAEgAAABQAAAAWAAAAGAAAABoAAAAcAAIAAAAEAAAABgAAAAgAAAAKAAAADAAAAA4AAAAQAAAAEgAAABQAAAAWAAAAGAAAABoAAAAcAAAAHgAAACAAAAAiAAAAJAAAACYAAAAoAAA=
  tileset/interior_brick_outer_edge_w: ACgABAAoAAYAKAAIACgACgAoAAwAKAAOACgAEAAoABIAKAAUACgAFgAoABgAKAAa
  tileset/wall_interior_brick_outer_edge_s: AAAAIAACACAABAAgAAYAIAAIACAACgAgAAwAIAAOACAAEAAgABIAIAAUACAAFgAgABgAIAAaACAAHAAgAAIABAAEAAQABgAEAAgABAAKAAQADAAEAA4ABAAQAAQAEgAEABQABAAWAAQAGAAEABoABAAcAAQAHgAEACAABAAiAAQAJAAEACYABAAoAAQAHgAgACAAIAAiACAAJAAgACYAIAAoACA=
  tileset/interior_brick_outer_edge_n: ABYAHAAYABwAGgAcABwAHAAUABwABAAcAAYAHAAIABwACgAcAAwAHAAOABwAEAAcABIAHAAeABwAIAAcACIAHAAkABwAJgAc
  tileset/stone_bordered_outer_edge_sw: AAoAHA==
  tileset/bar_horiz_c: AAQACwAGAAsACAAL
  tileset/stone_bordered_outer_edge_e: ABIAGg==
  tileset/fancy_carpet_outer_edge_nw: AB4ACg==
  tileset/interior_brick_outer_edge_se: ACoAHg==
  tileset/chair06: AAUAGQAFABUABQAR
  tileset/stone_bordered_outer_edge_s: AAwAHAAOABwAEAAc
  01entry_light: AAwAGA==
  tileset/stone_bordered_base: AAwAGgAOABoAEAAa
  tileset/fancy_carpet_outer_edge_w: AB4AFgAeABQAHgASAB4AEAAeAAwAHgAO
  tileset/cabinet_top_02: ACIAGg==
  tileset/fancy_carpet_outer_edge_n: ACAACgAiAAo=
  tileset/interior_brick_inner_edge_ne: AAIAHA==
  tileset/stone_bordered_outer_edge_nw: AAoAGA==
  tileset/fancy_carpet_base: ACAAFgAgABQAIAASACAAEAAgAA4AIAAMACIADAAiAA4AIgAQACIAEgAiABQAIgAW
  tileset/stone_bordered_outer_edge_ne: ABIAGA==
  props/dummy: AA8ABwASAAcAFQAH
  tileset/sack_stack: ACYAGAAkABg=
  tileset/banner_red: AAUABAAlAAQ=
  tileset/fancy_carpet_outer_edge_s: ACAAGAAiABg=
  tileset/table01: AAcACQ==
  tileset/interior_brick_inner_edge_sw: ACgAAg==
  tileset/fancy_carpet_outer_edge_e: ACQADAAkAA4AJAAQACQAEgAkABQAJAAW
  tileset/cabinet_top_03: AB4AGg==
  tileset/fancy_carpet_outer_edge_sw: AB4AGA==
  tileset/interior_brick_inner_edge_se: AAIAAg==
  tileset/fancy_carpet_outer_edge_ne: ACQACg==
  tileset/fancy_carpet_outer_edge_se: ACQAGA==
  props/barrel: ACYAFw==
  tileset/bar_horiz_w: AAoACw==
  tileset/banner_shield_grey: AB4ABAALAAQ=
  tileset/interior_brick_outer_edge_e: ACoAAAACABoAAgAYAAIAFgACABQAAgASAAIAEAACAAQAAgAGAAIACAACAAoAAgAMAAIADgAqAAIAKgAEACoABgAqAAgAKgAKACoADAAqAA4AKgAQACoAEgAqABQAKgAWACoAGAAqABoAKgAc
  tileset/interior_wood02_base: AAwAFAAMABYADAAYAA4AFAAOABYADgAYABAAFAAQABYAEAAYABIAFAASABYAEgAYABIAGgAUABQAFAAWABQAGgAWABQAFgAWABYAGAAWABoAGAAUABgAFgAYABgAGAAaABoAFAAaABYAGgAYABoAGgAcABQAHAAWABwAGgAeABQAHgAWAB4AGgAgABoAIgAaACQAGgAmABoAIAAYACIAGAAkABgAJgAYACQAFgAmABYAJAAUACYAFAAkABIAJAAQACYAEAAgAAYAIgAGACQABgAmAAYAJgAIACYADAAmAA4AJAAKACQADAAkAA4AIgAIACIACgAgAAgAIAAKAB4ACAAeAAoAHAAIABwACgAaAAgAGgAKABgACAAYAAoAFgAIABYACgAUAAgAFAAKABIACAAOAAgAEAAIAAwACgAOAAoAEAAKAAwADAAMABAADAASAA4ADAAOAA4ADgAQAA4AEgAQAAwAEAAOABAAEAAQABIAEgAMABIADgASABAAEgASABQADAAUAA4AFAAQABQAEgAWAAwAFgAOABYAEAAYAAwAGgAMABwADAAeAAwAGgAOABwADgAeAA4AGAAQABoAEAAcABAAHgAQABgAEgAaABIAHAASAB4AEgAEAAgABgAIAAgACAAKAAgABgAKAAgACgAEAAwABgAMAAgADAAKAAwABAAOAAYADgAKAA4ABAAQAAYAEAAIABAACgAQAAQAEgAGABIACAASAAoAEgAEABQABgAUAAgAFAAEABYABgAWAAgAFgAKABYABAAYAAYAGAAIABgACgAYAAQAGgAGABoACAAaAAoAGgAEABwABgAcAAgAHAAKABwACgAUABQAGAAcABgAHgAYACYAEgAkAAgAJgAKABgADgAWABIADAAOAAgADgAEAAoACgAKAAwACAASAAo=
  tileset/bar_vert_west_c: ABwAGgAcABgAHAAW
  tileset/crate_small: AAQABw==
elevation: AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgICAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgAAAAAAAAICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA